/* NAME- SATYAJIT BEHERA
   ROLL NO-21AG10034
   DEPT- AGRICULTURE AND FOOD ENGINEERING
   SECTION-03
   SOFTWARE- CODEBLOCK*/
#include <stdio.h>
int main()
{
//Here, I made 4 arrays to store the various repairing costs of each machine by different vendors
    int m1[4],b1[4];
    int m2[4],b2[4];
    int m3[4],b3[4];
    int m4[4],b4[4];
    int i[4],j,k;
    int v[4];
    int small=0;
    int sum=0;
    int temp=0;
    printf("Enter the prices of M1:\n");
    for(j=0;j<4;j++)
    {
        scanf("%d",&m1[j]);
        b1[j]=m1[j];
    }
    printf("Enter the prices of M2:\n");
    for(j=0;j<4;j++)
    {
        scanf("%d",&m2[j]);
        b2[j]=m2[j];
    }
    printf("Enter the prices of M3:\n");
    for(j=0;j<4;j++)
    {

        scanf("%d",&m3[j]);
        b3[j]=m3[j];
    }
    printf("Enter the prices of M4:\n");
    for(j=0;j<4;j++)
    {
        scanf("%d",&m4[j]);
        b4[j]=m4[j];
    }
    small=m1[0];
    for(j=1;j<4;j++)
    {
        if(small>m1[j])
        {
            small=m1[j];
            i[0]=j;
        }
    }
    small=m2[0];
     for(j=1;j<4;j++)
    {
        if(small>m2[j])
        {
            small=m2[j];
            i[1]=j;
        }
    }
    small=m3[0];
     for(j=1;j<4;j++)
    {
        if(small>m3[j])
        {
            small=m3[j];
            i[2]=j;
        }
    }
    small=m4[0];
     for(j=1;j<4;j++)
    {
        if(small>m4[j])
        {
            small=m4[j];
            i[3]=j;
        }
    }
//Here I already found out the vendor numbers so now I will just sort the arrays in ascending order for my convenience
    for(k=0;k<4;k++)
    {
        small=m1[k];
     for(j=k+1;j<4;j++)
     {
         if(m1[k]>m1[j])
         {
             m1[k]=m1[j];
             m1[j]=small;
         }
     }
    }
    for(k=0;k<4;k++)
    {
        small=m2[k];
     for(j=k+1;j<4;j++)
     {
         if(m2[k]>m2[j])
         {
             m2[k]=m2[j];
             m2[j]=small;
         }
     }
    }
    for(k=0;k<4;k++)
    {
        small=m3[k];
     for(j=k+1;j<4;j++)
     {
         if(m3[k]>m3[j])
         {
             m3[k]=m3[j];
             m3[j]=small;
         }
     }
    }
    for(k=0;k<4;k++)
    {
        small=m4[k];
     for(j=k+1;j<4;j++)
     {
         if(m4[k]>m1[j])
         {
             m4[k]=m4[j];
             m4[j]=small;
         }
     }
    }
    v[0]=i[0];
    v[1]=i[1];
    v[2]=i[2];
    v[3]=i[3];
//Here I check all the conditions of ties
    if(i[0]!=i[1]&&i[0]!=i[2]&&i[0]!=i[3]&&i[1]!=i[2]&&i[1]!=i[3]&&i[2]!=i[3])
        sum=m1[0]+m2[0]+m3[0]+m4[0];
    else if(i[0]==i[1]&&i[0]!=i[2]&&i[0]!=i[3]&&i[1]!=i[2]&&i[1]!=i[3]&&i[2]!=i[3])
        {
            if(m1[0]+m2[1]+m3[0]+m4[0]>m1[1]+m2[0]+m3[0]+m4[0])
                {
                    sum=m1[1]+m2[0]+m3[0]+m4[0];
                    for(j=0;j<4;j++)
                    {
                        if(b1[j]==m1[1])
                            v[0]=j;
                    }
                }
            else
            {
                sum=m1[0]+m2[1]+m3[0]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b2[j]==m2[1])
                        v[1]=j;
                }
                }
        }
    else if(i[0]!=i[1]&&i[0]==i[2]&&i[0]!=i[3]&&i[1]!=i[2]&&i[1]!=i[3]&&i[2]!=i[3])
        {
            if(m1[0]+m2[0]+m3[1]+m4[0]>m1[1]+m2[0]+m3[0]+m4[0])
                {sum=m1[1]+m2[0]+m3[0]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b1[j]==m1[1])
                        v[0]=j;
                }}
            else
                {sum=m1[0]+m2[0]+m3[1]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b3[j]==m3[1])
                        v[2]=j;
                }}
        }
    else if(i[0]!=i[1]&&i[0]!=i[2]&&i[0]==i[3]&&i[1]!=i[2]&&i[1]!=i[3]&&i[2]!=i[3])
        {
            if(m1[0]+m2[0]+m3[0]+m4[1]>m1[1]+m2[0]+m3[0]+m4[0])
                {sum=m1[1]+m2[0]+m3[0]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b1[j]==m1[1])
                        v[0]=j;
                }}
            else
                {sum=m1[0]+m2[0]+m3[0]+m4[1];
                for(j=0;j<4;j++)
                {
                    if(b4[j]==m4[1])
                        v[3]=j;
                }}
        }
    else if(i[0]!=i[1]&&i[0]!=i[2]&&i[0]!=i[3]&&i[1]==i[2]&&i[1]!=i[3]&&i[2]!=i[3])
        {
            if(m1[0]+m2[0]+m3[1]+m4[0]>m1[0]+m2[1]+m3[0]+m4[0])
                {sum=m1[0]+m2[1]+m3[0]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b2[j]==m2[1])
                        v[1]=j;
                }}
            else
                {sum=m1[0]+m2[0]+m3[1]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b3[j]==m3[1])
                        v[2]=j;
                }}
        }
    else if(i[0]!=i[1]&&i[0]!=i[2]&&i[0]!=i[3]&&i[1]!=i[2]&&i[1]==i[3]&&i[2]!=i[3])
        {
            if(m1[0]+m2[0]+m3[0]+m4[1]>m1[0]+m2[1]+m3[0]+m4[0])
                {sum=m1[0]+m2[1]+m3[0]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b2[j]==m2[1])
                        v[1]=j;
                }}
            else
                {sum=m1[0]+m2[0]+m3[0]+m4[1];
                for(j=0;j<4;j++)
                {
                    if(b4[j]==m4[1])
                        v[3]=j;
                }}
        }
        else if(i[0]!=i[1]&&i[0]!=i[2]&&i[0]!=i[3]&&i[1]!=i[2]&&i[1]==i[3]&&i[2]==i[3])
        {
            if(m1[0]+m2[0]+m3[0]+m4[1]>m1[0]+m2[0]+m3[1]+m4[0])
                {sum=m1[0]+m2[0]+m3[1]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b3[j]==m3[1])
                        v[2]=j;
                }}
            else
                {sum=m1[0]+m2[0]+m3[0]+m4[1];
                for(j=0;j<4;j++)
                {
                    if(b4[j]==m4[1])
                        v[3]=j;
                }}
        }
    else if(i[0]==i[1]&&i[0]==i[2]&&i[0]!=i[3])
        {
            if(m1[0]+m2[1]+m3[1]+m4[0]<m1[1]+m2[0]+m3[1]+m4[0]&&m1[0]+m2[1]+m3[1]+m4[0]<m1[1]+m2[1]+m3[0]+m4[0])
                {sum=m1[0]+m2[1]+m3[1]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b3[j]==m3[1])
                        v[2]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b2[j]==m2[1])
                        v[1]=j;
                }}
            else if(m1[1]+m2[0]+m3[1]+m4[0]<m1[0]+m2[1]+m3[1]+m4[0]&&m1[1]+m2[0]+m3[1]+m4[0]<m1[1]+m2[1]+m3[0]+m4[0])
                {sum=m1[1]+m2[0]+m3[1]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b1[j]==m1[1])
                        v[0]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b3[j]==m3[1])
                        v[2]=j;
                }
                }
            else
            {
                {sum=m1[1]+m2[1]+m3[0]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b1[j]==m1[1])
                        v[0]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b2[j]==m2[1])
                        v[1]=j;
                }
                }
            }
        }
        else if(i[0]!=i[1]&&i[0]==i[2]&&i[0]==i[3])
        {
            if(m1[0]+m2[0]+m3[1]+m4[1]<m1[1]+m2[0]+m3[0]+m4[1]&&m1[0]+m2[0]+m3[1]+m4[1]<m1[1]+m2[0]+m3[1]+m4[0])
                {sum=m1[0]+m2[0]+m3[1]+m4[1];
                for(j=0;j<4;j++)
                {
                    if(b3[j]==m3[1])
                        v[2]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b4[j]==m4[1])
                        v[3]=j;
                }}
            else if(m1[1]+m2[0]+m3[0]+m4[1]<m1[0]+m2[0]+m3[1]+m4[1]&&m1[1]+m2[0]+m3[0]+m4[1]<m1[1]+m2[0]+m3[1]+m4[0])
                {sum=m1[1]+m2[0]+m3[0]+m4[1];
                for(j=0;j<4;j++)
                {
                    if(b1[j]==m1[1])
                        v[0]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b4[j]==m4[1])
                        v[3]=j;
                }
                }
            else
            {
                {sum=m1[1]+m2[0]+m3[1]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b1[j]==m1[1])
                        v[0]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b3[j]==m3[1])
                        v[2]=j;
                }
                }
            }
        }
        else if(i[0]==i[1]&&i[0]!=i[2]&&i[0]==i[3])
        {
            if(m1[0]+m2[1]+m3[0]+m4[1]<m1[1]+m2[0]+m3[0]+m4[1]&&m1[0]+m2[1]+m3[0]+m4[1]<m1[1]+m2[1]+m3[0]+m4[0])
                {sum=m1[0]+m2[1]+m3[0]+m4[1];
                for(j=0;j<4;j++)
                {
                    if(b4[j]==m4[1])
                        v[3]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b2[j]==m2[1])
                        v[1]=j;
                }}
            else if(m1[1]+m2[0]+m3[0]+m4[1]<m1[0]+m2[1]+m3[1]+m4[0]&&m1[1]+m2[0]+m3[0]+m4[1]<m1[1]+m2[1]+m3[0]+m4[0])
                {sum=m1[1]+m2[0]+m3[0]+m4[1];
                for(j=0;j<4;j++)
                {
                    if(b1[j]==m1[1])
                        v[0]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b4[j]==m4[1])
                        v[3]=j;
                }
                }
            else
            {
                {sum=m1[1]+m2[1]+m3[0]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b1[j]==m1[1])
                        v[0]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b2[j]==m2[1])
                        v[1]=j;
                }
                }
            }
        }
        else if(i[1]!=i[0]&&i[1]==i[2]&&i[1]==i[3])
        {
            if(m1[0]+m2[0]+m3[1]+m4[1]<m1[0]+m2[1]+m3[0]+m4[1]&&m1[0]+m2[0]+m3[1]+m4[1]<m1[0]+m2[1]+m3[1]+m4[0])
                {sum=m1[0]+m2[0]+m3[1]+m4[1];
                for(j=0;j<4;j++)
                {
                    if(b4[j]==m4[1])
                        v[3]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b3[j]==m3[1])
                        v[2]=j;
                }}
            else if(m1[0]+m2[1]+m3[0]+m4[1]<m1[0]+m2[0]+m3[1]+m4[1]&&m1[0]+m2[1]+m3[0]+m4[1]<m1[0]+m2[1]+m3[1]+m4[0])
                {sum=m1[0]+m2[1]+m3[0]+m4[1];
                for(j=0;j<4;j++)
                {
                    if(b2[j]==m2[1])
                        v[1]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b4[j]==m4[1])
                        v[3]=j;
                }
                }
            else
            {
                {sum=m1[0]+m2[1]+m3[1]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b3[j]==m3[1])
                        v[2]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b2[j]==m2[1])
                        v[1]=j;
                }
                }
            }
        }
        else if(i[0]==i[1]&&i[0]==i[2]&&i[0]==i[3])
        {
            if(m1[0]+m2[1]+m3[1]+m4[1]<m1[1]+m2[0]+m3[1]+m4[1]&&m1[0]+m2[1]+m3[1]+m4[1]<m1[1]+m2[1]+m3[0]+m4[1]&&m1[0]+m2[1]+m3[1]+m4[1]<m1[1]+m2[1]+m3[1]+m4[0])
                {sum=m1[0]+m2[1]+m3[1]+m4[1];
                for(j=0;j<4;j++)
                {
                    if(b4[j]==m4[1])
                        v[3]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b2[j]==m2[1])
                        v[1]=j;
                }
                 for(j=0;j<4;j++)
                {
                    if(b3[j]==m3[1])
                        v[2]=j;
                }
                }
            else if(m1[1]+m2[0]+m3[1]+m4[1]<m1[0]+m2[1]+m3[1]+m4[1]&&m1[1]+m2[0]+m3[1]+m4[1]<m1[1]+m2[1]+m3[0]+m4[1]&&m1[1]+m2[0]+m3[1]+m4[1]<m1[1]+m2[1]+m3[1]+m4[0])
                {sum=m1[1]+m2[0]+m3[1]+m4[1];
                for(j=0;j<4;j++)
                {
                    if(b1[j]==m1[1])
                        v[0]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b4[j]==m4[1])
                        v[3]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b3[j]==m3[1])
                        v[2]=j;
                }
                }
            else if(m1[1]+m2[1]+m3[1]+m4[0]<m1[0]+m2[1]+m3[1]+m4[1]&&m1[1]+m2[1]+m3[1]+m4[0]<m1[1]+m2[1]+m3[0]+m4[1]&&m1[1]+m2[1]+m3[1]+m4[0]<m1[1]+m2[0]+m3[1]+m4[1])
                {sum=m1[1]+m2[0]+m3[1]+m4[0];
                for(j=0;j<4;j++)
                {
                    if(b1[j]==m1[1])
                        v[0]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b2[j]==m2[1])
                        v[1]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b3[j]==m3[1])
                        v[2]=j;
                }
                }
            else
            {
                {sum=m1[1]+m2[1]+m3[0]+m4[1];
                for(j=0;j<4;j++)
                {
                    if(b1[j]==m1[1])
                        v[0]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b2[j]==m2[1])
                        v[1]=j;
                }
                for(j=0;j<4;j++)
                {
                    if(b4[j]==m4[1])
                        v[3]=j;
                }
                }
            }
        }
        printf("The total sum of the repairing of all the amchines comes out to be %d\n",sum);
        printf("Machine 1= Vendor %d\n",v[0]);
        printf("Machine 2= Vendor %d\n",v[1]);
        printf("Machine 3= Vendor %d\n",v[2]);
        printf("Machine 4= Vendor %d\n",v[3]);
}
