#include <stdio.h>
#include <math.h>
int main()          //program to compare Tp from predefined values and user input value.
{
    double alpha,rho,Rs,Ts,D,Tp;                    //declaring variables as double.
    printf("Enter the values accordingly.\n");
    printf("aplha = ");                             //taking alpha from user.
    scanf("%lf",&alpha);

    printf("rho = ");                               //taking rho from user.
    scanf("%lf",&rho);

    printf("Rs = ");                                //taking Rs from user.
    scanf("%lf",&Rs);

    printf("Ts = ");                                //taking Ts from user.
    scanf("%lf",&Ts);

    printf("D = ");                                 //taking D from user.
    scanf("%lf",&D);

    Tp=Ts*(sqrt(Rs*(sqrt((1-alpha)/rho))/(2*D)));   //value of Tp generated after user input.
    printf("User input and generated Tp = %le",Tp); //showing Tp

    alpha=0.306;                                    //predefined values of alpha,rho,Rs,Ts,D
    rho=1.2;
    Rs=6.96e8;
    Ts=1.3654e-11;
    D=1.496e11;

    Tp=Ts*(sqrt(Rs*(sqrt((1-alpha)/rho))/(2*D)));    //value of Tp from predefined values.
    printf("\nTp generated by computer from defined values = %le\n",Tp);
    return 0;
}




