/*Section 14 Name:Gurram Dhanunjay RollNo:22CS10029 Assignment:5 Description:Finding sum of given series using functions*/ #include int n;
 int maxi(int b[]) { int count=0,max;
 while (countb[count]) continue;
 else max=b[count];
 } count++;
 } return max;
 } int mini(int b[]) { int count=0,min;
 while (count int n;
 int maxi(int b[]) { int count=0,max;
 while (countb[count]) continue;
 else max=b[count];
 } count++;
 } return max;
 } int mini(int b[]) { int count=0,min;
 while (count",count);
 if (a[j]>=i && a[j]<=i+d-1) printf("%d",a[j]);
} printf("\n");
 count++;
 }} } count++;
 } return min;
 }} int main() { int b,i,j,min,max,d,count;
 int maxi(int b[]) ;
 int mini(int b[]);
 int a[10];
 n=10;
 printf("Enter the numbers\n");
 for (i=0;
i",count);
 if (a[j]>=i && a[j]<=i+d-1) printf("%d",a[j]);
} printf("\n");
 count++;
 }}